/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:b86b8f8a-59c9-4377-8768-668b23466628",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_2LtdZ7IGh",
    "aws_user_pools_web_client_id": "cs7c11i0es34vd1l34b8an4p5",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://usaf2arumzaz7kn2buhgdltyhu.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "0ba9558562034f979785f6e9f1efa510",
    "aws_mobile_analytics_app_region": "us-west-2"
};


export default awsmobile;
